AWS_UPLOAD_BUCKET = "blog19"

AWS_UPLOAD_USERNAME = "blog19"

AWS_UPLOAD_GROUP = "sparktake"

AWS_UPLOAD_REGION = "ap-southeast-1"

AWS_UPLOAD_ACCESS_KEY_ID = "AKIAJVQOLWMGS4XYJKGQ"

AWS_UPLOAD_SECRET_KEY = "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"