# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170919_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date(2017, 9, 20)),
        ),
    ]
