# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170923_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
