# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20171026_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='slug',
            new_name='imageslug',
        ),
    ]
