# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_postimage_imageslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='imageslug',
            field=models.SlugField(null=True),
        ),
    ]
