# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20171229_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
