# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20171229_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(default='sth.img'),
            preserve_default=False,
        ),
    ]
