# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20180109_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(),
        ),
    ]
